### ISSUE TITLE
arguments missing

### ISSUE THREAD

**Issue by brainysmurf** [imartinat/mb2sqldb#4]
After adding `end_term_id` I still get the following traceback:

/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:34745
    const error2 = new PrismaClientValidationError(renderErrorStr(validationCallsite));
                   ^

PrismaClientValidationError: 
Invalid `prisma.section.create()` invocation:

{
  data: {
    id: 10149456,
    name: 'BP Heatlh (Grade 12)',
+   start_term_id: Int,
+   end_term_id: Int,
    teachers: {
      connect: []
    },
?   students?: {
?     create?: StudentCreateWithoutClassesInput | StudentCreateWithoutClassesInput | StudentUncheckedCreateWithoutClassesInput | StudentUncheckedCreateWithoutClassesInput,
?     connectOrCreate?: StudentCreateOrConnectWithoutClassesInput | StudentCreateOrConnectWithoutClassesInput,
?     connect?: StudentWhereUniqueInput | StudentWhereUniqueInput
?   },
?   termGrades?: {
?     create?: TermGradeCreateWithoutClassInput | TermGradeCreateWithoutClassInput | TermGradeUncheckedCreateWithoutClassInput | TermGradeUncheckedCreateWithoutClassInput,
?     connectOrCreate?: TermGradeCreateOrConnectWithoutClassInput | TermGradeCreateOrConnectWithoutClassInput,
?     connect?: TermGradeWhereUniqueInput | TermGradeWhereUniqueInput
?   }
  }
}

Argument start_term_id for data.start_term_id is missing.
Argument end_term_id for data.end_term_id is missing.

Note: Lines with + are required, lines with ? are optional.

    at Object.validate (/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:34745:20)
    at PrismaClient._executeRequest (/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:39720:17)
    at consumer (/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:39661:23)
    at /Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:39665:49
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at PrismaClient._request (/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:39665:27)
    at request (/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:39770:77)
    at _callback (/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:39978:14)
    at PrismaPromise.then (/Users/adammorris/src/mb2sqldb/node_modules/@prisma/client/runtime/index.js:39985:23) {
  clientVersion: '3.5.0'
}

**Comment by imartinat** [comment]
Do you have term ids in start_term_id and end_term_id in this class in ManageBac?
